<?php

use Illuminate\Database\Seeder;

class NationalitiesTableSeeder extends Seeder
{
    private $nationalities;

    private function initNationalitiesValues()
    {
        $this->nationalities = array(
            array('id' => 1, 'name' => 'Afghan'),
            array('id' => 2, 'name' => 'Albanian'),
            array('id' => 3, 'name' => 'Algerian'),
            array('id' => 4, 'name' => 'American'),
            array('id' => 5, 'name' => 'Andorran'),
            array('id' => 6, 'name' => 'Angolan'),
            array('id' => 7, 'name' => 'Antiguans'),
            array('id' => 8, 'name' => 'Argentinean'),
            array('id' => 9, 'name' => 'Armenian'),
            array('id' => 10, 'name' => 'Australian'),
            array('id' => 11, 'name' => 'Austrian'),
            array('id' => 12, 'name' => 'Azerbaijani'),
            array('id' => 13, 'name' => 'Bahamian'),
            array('id' => 14, 'name' => 'Bahraini'),
            array('id' => 15, 'name' => 'Bangladeshi'),
            array('id' => 16, 'name' => 'Barbadian'),
            array('id' => 17, 'name' => 'Barbudans'),
            array('id' => 18, 'name' => 'Batswana'),
            array('id' => 19, 'name' => 'Belarusian'),
            array('id' => 20, 'name' => 'Belgian'),
            array('id' => 21, 'name' => 'Belizean'),
            array('id' => 22, 'name' => 'Beninese'),
            array('id' => 23, 'name' => 'Bhutanese'),
            array('id' => 24, 'name' => 'Bolivian'),
            array('id' => 25, 'name' => 'Bosnian'),
            array('id' => 26, 'name' => 'Brazilian'),
            array('id' => 27, 'name' => 'British'),
            array('id' => 28, 'name' => 'Bruneian'),
            array('id' => 29, 'name' => 'Bulgarian'),
            array('id' => 30, 'name' => 'Burkinabe'),
            array('id' => 31, 'name' => 'Burmese'),
            array('id' => 32, 'name' => 'Burundian'),
            array('id' => 33, 'name' => 'Cambodian'),
            array('id' => 34, 'name' => 'Cameroonian'),
            array('id' => 35, 'name' => 'Canadian'),
            array('id' => 36, 'name' => 'Cape Verdean'),
            array('id' => 37, 'name' => 'Central African'),
            array('id' => 38, 'name' => 'Chadian'),
            array('id' => 39, 'name' => 'Chilean'),
            array('id' => 40, 'name' => 'Chinese'),
            array('id' => 41, 'name' => 'Colombian'),
            array('id' => 42, 'name' => 'Comoran'),
            array('id' => 43, 'name' => 'Congolese'),
            array('id' => 44, 'name' => 'Costa Rican'),
            array('id' => 45, 'name' => 'Croatian'),
            array('id' => 46, 'name' => 'Cuban'),
            array('id' => 47, 'name' => 'Cypriot'),
            array('id' => 48, 'name' => 'Czech'),
            array('id' => 49, 'name' => 'Danish'),
            array('id' => 50, 'name' => 'Djibouti'),
            array('id' => 51, 'name' => 'Dominican'),
            array('id' => 52, 'name' => 'Dutch'),
            array('id' => 53, 'name' => 'East Timorese'),
            array('id' => 54, 'name' => 'Ecuadorean'),
            array('id' => 55, 'name' => 'Egyptian'),
            array('id' => 56, 'name' => 'Emirian'),
            array('id' => 57, 'name' => 'Equatorial Guinean'),
            array('id' => 58, 'name' => 'Eritrean'),
            array('id' => 59, 'name' => 'Estonian'),
            array('id' => 60, 'name' => 'Ethiopian'),
            array('id' => 61, 'name' => 'Fijian'),
            array('id' => 62, 'name' => 'Filipino'),
            array('id' => 63, 'name' => 'Finnish'),
            array('id' => 64, 'name' => 'French'),
            array('id' => 65, 'name' => 'Gabonese'),
            array('id' => 66, 'name' => 'Gambian'),
            array('id' => 67, 'name' => 'Georgian'),
            array('id' => 68, 'name' => 'German'),
            array('id' => 69, 'name' => 'Ghanaian'),
            array('id' => 70, 'name' => 'Greek'),
            array('id' => 71, 'name' => 'Grenadian'),
            array('id' => 72, 'name' => 'Guatemalan'),
            array('id' => 73, 'name' => 'Guinea-Bissauan'),
            array('id' => 74, 'name' => 'Guinean'),
            array('id' => 75, 'name' => 'Guyanese'),
            array('id' => 76, 'name' => 'Haitian'),
            array('id' => 77, 'name' => 'Herzegovinian'),
            array('id' => 78, 'name' => 'Honduran'),
            array('id' => 79, 'name' => 'Hungarian'),
            array('id' => 80, 'name' => 'Icelander'),
            array('id' => 81, 'name' => 'Indian'),
            array('id' => 82, 'name' => 'Indonesian'),
            array('id' => 83, 'name' => 'Iranian'),
            array('id' => 84, 'name' => 'Iraqi'),
            array('id' => 85, 'name' => 'Irish'),
            array('id' => 86, 'name' => 'Israeli'),
            array('id' => 87, 'name' => 'Italian'),
            array('id' => 88, 'name' => 'Ivorian'),
            array('id' => 89, 'name' => 'Jamaican'),
            array('id' => 90, 'name' => 'Japanese'),
            array('id' => 91, 'name' => 'Jordanian'),
            array('id' => 92, 'name' => 'Kazakhstani'),
            array('id' => 93, 'name' => 'Kenyan'),
            array('id' => 94, 'name' => 'Kittian and Nevisian'),
            array('id' => 95, 'name' => 'Kuwaiti'),
            array('id' => 96, 'name' => 'Kyrgyz'),
            array('id' => 97, 'name' => 'Laotian'),
            array('id' => 98, 'name' => 'Latvian'),
            array('id' => 99, 'name' => 'Lebanese'),
            array('id' => 100, 'name' => 'Liberian'),
            array('id' => 101, 'name' => 'Libyan'),
            array('id' => 102, 'name' => 'Liechtensteiner'),
            array('id' => 103, 'name' => 'Lithuanian'),
            array('id' => 104, 'name' => 'Luxembourger'),
            array('id' => 105, 'name' => 'Macedonian'),
            array('id' => 106, 'name' => 'Malagasy'),
            array('id' => 107, 'name' => 'Malawian'),
            array('id' => 108, 'name' => 'Malaysian'),
            array('id' => 109, 'name' => 'Maldivan'),
            array('id' => 110, 'name' => 'Malian'),
            array('id' => 111, 'name' => 'Maltese'),
            array('id' => 112, 'name' => 'Marshallese'),
            array('id' => 113, 'name' => 'Mauritanian'),
            array('id' => 114, 'name' => 'Mauritian'),
            array('id' => 115, 'name' => 'Mexican'),
            array('id' => 116, 'name' => 'Micronesian'),
            array('id' => 117, 'name' => 'Moldovan'),
            array('id' => 118, 'name' => 'Monacan'),
            array('id' => 119, 'name' => 'Mongolian'),
            array('id' => 120, 'name' => 'Moroccan'),
            array('id' => 121, 'name' => 'Mosotho'),
            array('id' => 122, 'name' => 'Motswana'),
            array('id' => 123, 'name' => 'Mozambican'),
            array('id' => 124, 'name' => 'Namibian'),
            array('id' => 125, 'name' => 'Nauruan'),
            array('id' => 126, 'name' => 'Nepalese'),
            array('id' => 127, 'name' => 'Netherlander'),
            array('id' => 128, 'name' => 'New Zealander'),
            array('id' => 129, 'name' => 'Ni-Vanuatu'),
            array('id' => 130, 'name' => 'Nicaraguan'),
            array('id' => 131, 'name' => 'Nigerian'),
            array('id' => 132, 'name' => 'Nigerien'),
            array('id' => 133, 'name' => 'North Korean'),
            array('id' => 134, 'name' => 'Northern Irish'),
            array('id' => 135, 'name' => 'Norwegian'),
            array('id' => 136, 'name' => 'Omani'),
            array('id' => 137, 'name' => 'Pakistani'),
            array('id' => 138, 'name' => 'Palauan'),
            array('id' => 139, 'name' => 'Panamanian'),
            array('id' => 140, 'name' => 'Papua New Guinean'),
            array('id' => 141, 'name' => 'Paraguayan'),
            array('id' => 142, 'name' => 'Peruvian'),
            array('id' => 143, 'name' => 'Polish'),
            array('id' => 144, 'name' => 'Portuguese'),
            array('id' => 145, 'name' => 'Qatari'),
            array('id' => 146, 'name' => 'Romanian'),
            array('id' => 147, 'name' => 'Russian'),
            array('id' => 148, 'name' => 'Rwandan'),
            array('id' => 149, 'name' => 'Saint Lucian'),
            array('id' => 150, 'name' => 'Salvadoran'),
            array('id' => 151, 'name' => 'Samoan'),
            array('id' => 152, 'name' => 'San Marinese'),
            array('id' => 153, 'name' => 'Sao Tomean'),
            array('id' => 154, 'name' => 'Saudi'),
            array('id' => 155, 'name' => 'Scottish'),
            array('id' => 156, 'name' => 'Senegalese'),
            array('id' => 157, 'name' => 'Serbian'),
            array('id' => 158, 'name' => 'Seychellois'),
            array('id' => 159, 'name' => 'Sierra Leonean'),
            array('id' => 160, 'name' => 'Singaporean'),
            array('id' => 161, 'name' => 'Slovakian'),
            array('id' => 162, 'name' => 'Slovenian'),
            array('id' => 163, 'name' => 'Solomon Islander'),
            array('id' => 164, 'name' => 'Somali'),
            array('id' => 165, 'name' => 'South African'),
            array('id' => 166, 'name' => 'South Korean'),
            array('id' => 167, 'name' => 'Spanish'),
            array('id' => 168, 'name' => 'Sri Lankan'),
            array('id' => 169, 'name' => 'Sudanese'),
            array('id' => 170, 'name' => 'Surinamer'),
            array('id' => 171, 'name' => 'Swazi'),
            array('id' => 172, 'name' => 'Swedish'),
            array('id' => 173, 'name' => 'Swiss'),
            array('id' => 174, 'name' => 'Syrian'),
            array('id' => 175, 'name' => 'Taiwanese'),
            array('id' => 176, 'name' => 'Tajik'),
            array('id' => 177, 'name' => 'Tanzanian'),
            array('id' => 178, 'name' => 'Thai'),
            array('id' => 179, 'name' => 'Togolese'),
            array('id' => 180, 'name' => 'Tongan'),
            array('id' => 181, 'name' => 'Trinidadian or Tobagonian'),
            array('id' => 182, 'name' => 'Tunisian'),
            array('id' => 183, 'name' => 'Turkish'),
            array('id' => 184, 'name' => 'Tuvaluan'),
            array('id' => 185, 'name' => 'Ugandan'),
            array('id' => 186, 'name' => 'Ukrainian'),
            array('id' => 187, 'name' => 'Uruguayan'),
            array('id' => 188, 'name' => 'Uzbekistani'),
            array('id' => 189, 'name' => 'Venezuelan'),
            array('id' => 190, 'name' => 'Vietnamese'),
            array('id' => 191, 'name' => 'Welsh'),
            array('id' => 192, 'name' => 'Yemenite'),
            array('id' => 193, 'name' => 'Zambian'),
            array('id' => 194, 'name' => 'Zimbabwean'),
            array('id' => 195, 'name' => 'palestine'),
        );
    }

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('nationalities')->delete();
        $this->initNationalitiesValues();
        foreach ($this->nationalities as $name)
            \DB::table('nationalities')->insert($name);
    }
}
